export default {
  male: [
    {'value': 'na', 'primaryText': 'No Sport Chosen'},
    {'value': 'baseball', 'primaryText': 'Baseball'},
    {'value': 'basketball', 'primaryText': 'Basketball'},
    {'value': 'cross_country', 'primaryText': 'Cross Country'},
    {'value': 'cycling', 'primaryText': 'Cycling'},
    {'value': 'football', 'primaryText': 'Football'},
    {'value': 'golf', 'primaryText': 'Golf'},
    {'value': 'ice_hockey', 'primaryText': 'Ice Hockey'},
    {'value': 'lacrosse', 'primaryText': 'Lacrosse'},
    {'value': 'olympic_weightlifting', 'primaryText': 'Olympic Weightlifting'},
    {'value': 'roller_hockey', 'primaryText': 'Roller Hockey'},
    {'value': 'rugby', 'primaryText': 'Rugby'},
    {'value': 'soccer', 'primaryText': 'Soccer'},
    {'value': 'swimming', 'primaryText': 'Swimming and Diving'},
    {'value': 'table_tennis', 'primaryText': 'Table Tennis'},
    {'value': 'tennis', 'primaryText': 'Tennis'},
    {'value': 'track_and_field', 'primaryText': 'Track and Field'},
    {'value': 'volleyball', 'primaryText': 'Volleyball'},
    {'value': 'water_polo', 'primaryText': 'Water Polo'},
    {'value': 'wrestling', 'primaryText': 'Wrestling'},
  ],
  female: [
    {'value': 'na', 'primaryText': 'No Sport Chosen'},
    {'value': 'basketball', 'primaryText': 'Basketball'},
    {'value': 'cross_country', 'primaryText': 'Cross Country'},
    {'value': 'cycling', 'primaryText': 'Cycling'},
    {'value': 'dance', 'primaryText': 'Dance'},
    {'value': 'field_hockey', 'primaryText': 'Field Hockey'},
    {'value': 'golf', 'primaryText': 'Golf'},
    {'value': 'gymnastics', 'primaryText': 'Gymnastics'},
    {'value': 'ice_hockey', 'primaryText': 'Ice Hockey'},
    {'value': 'lacrosse', 'primaryText': 'Lacrosse'},
    {'value': 'olympic_weightlifting', 'primaryText': 'Olympic Weightlifting'},
    {'value': 'rugby', 'primaryText': 'Rugby'},
    {'value': 'soccer', 'primaryText': 'Soccer'},
    {'value': 'softball', 'primaryText': 'Softball'},
    {'value': 'swimming', 'primaryText': 'Swimming and Diving'},
    {'value': 'synchro_skating', 'primaryText': 'Synchronized Skating'},
    {'value': 'synchro_swimming', 'primaryText': 'Synchronized Swimming'},
    {'value': 'table_tennis', 'primaryText': 'Table Tennis'},
    {'value': 'tennis', 'primaryText': 'Tennis'},
    {'value': 'track_and_field', 'primaryText': 'Track and Field'},
    {'value': 'volleyball', 'primaryText': 'Volleyball'},
    {'value': 'water_polo', 'primaryText': 'Water Polo'},
    {'value': 'wrestling', 'primaryText': 'Wrestling'},
  ],
};
